[workspace.package]
name = "{{project-name}}"
description = """{{description}}"""
authors = ["{{authors}}"]
readme = "README.md"
repository = "https://github.com/{{username}}/{{project-name}}.git"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["crates/{{project-name}}-bin"]
default-members = ["{{project-name}}-bin"]

[workspace.dependencies]
anyhow = {version = "*"}

