[workspace.package]
name = "{{project-name}}"
description = """{{description}}"""
authors = [""]
readme = "README.md"
repository = "https://github.com/siqpush/{{project-name}}.git"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["crates/lib","crates/bin"]
default-members = ["crates/bin"]

[workspace.dependencies]


